### ISSUE TITLE
smx

### ISSUE THREAD

**Issue by PotatoSUS** [Halqq/AuroraPublic#1]
onde esta o doctor swag?

**Comment by JohnShiozo** [comment]
java.lang.NullPointerException

**Comment by Halqq** [comment]
> onde esta o doctor swag?

doctor swag esta na china

**Comment by PotatoSUS** [comment]
java.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
java.lang.NullPointerException
